### ISSUE TITLE
Colour blindness

### ISSUE THREAD

**Issue by MarcinKosinski** [karthik/wesanderson#12]
Hi!
Thanks for creating such a useful package. 
One thing I'd like to pinpoint: I opened wes anderson palletes with Deuteranomaly colour blindenss sicknes filter [http://en.wikipedia.org/wiki/Color_blindness#Anomalous_trichromacy](http://en.wikipedia.org/wiki/Color_blindness#Anomalous_trichromacy) and those palletes all look the same :) They are not adapted for people with Deuteranomaly colour blindenss sicknes (most common—6% of males, 0.4% of females).
![bez tytulu](https://cloud.githubusercontent.com/assets/6773454/5793477/fa081e9c-9f44-11e4-9787-1a5135da6917.jpg)

**Comment by karthik** [comment]
Thanks for the note. I have no idea how to make these palettes color blind friendly. So for the time being I'm going to close this up. If I can add an option to make it color blind safe, I'll do it in the future.

**Comment by MarcinKosinski** [comment]
I suggest you read this [shor article from Nature]((http://www.nature.com/nmeth/journal/v8/n6/full/nmeth.1618.html)) about color blindness and how to avoid 'inappropriate' colors.

**Comment by MarcinKosinski** [comment]
http://www.nature.com/nmeth/journal/v8/n6/full/nmeth.1618.html
