### ISSUE TITLE
exposed Latex on CRAN page...

### ISSUE THREAD

**Issue by benmarwick** [karthik/wesanderson#13]
....at the tumblr URL. Is that supposed to be there? Hard to imagine it's tolerated by CRAN, given  recent comments about capitalisation, etc. Anyway, just curious. 

http://cran.r-project.org/web/packages/wesanderson/index.html

![clipboard02](https://cloud.githubusercontent.com/assets/1262179/5797725/13f9319a-9f74-11e4-86b1-7a3068daa735.png)

**Comment by karthik** [comment]
This was before the rules got stricter. So it will be gone in the next update.
