### ISSUE TITLE
No wesanderson colors after upgrading to RStudio Version 1.1.383 

### ISSUE THREAD

**Issue by j-tamad** [karthik/wesanderson#29]
I re-installed the package and loaded it, but the plot is just greyscale. RColorBrewer is ok.

Also this when I tried to run code from http://www.sthda.com/

> barplot(c(2,5,7), col=wes.palette(n=3, name="GrandBudapest"))
Error in wes.palette(n = 3, name = "GrandBudapest") : 
  could not find function "wes.palette"

**Comment by kbroman** [comment]
`wes.palette()` is now `wes_palette()`, and some of the palettes have been re-named, try:

```
library(wesanderson)
barplot(c(2,5,7), col=wes_palette(n=3, name="GrandBudapest1"))
```
