### ISSUE TITLE
five zissou colors ... too few

### ISSUE THREAD

**Issue by dlpd** [karthik/wesanderson#31]
```
Error: Insufficient values in manual scale. 6 needed but only 5 provided.
```

Are you finding what you were looking for... out here with me? I hope so.

**Comment by karthik** [comment]
The palette only has 5 colors. And you need six in your example. So you'll need to choose a different palette.

**Comment by karthik** [comment]
It's hard to help further without a reproducible example.

**Comment by karthik** [comment]
Got it 🙏. Will look into it for the next release. Current release is in queue.
