### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bryevdv** [karthik/wesanderson#36]
What license is this under?

**Comment by karthik** [comment]
It is under [MIT](https://github.com/karthik/wesanderson/blob/master/DESCRIPTION#L16)

**Comment by bryevdv** [comment]
@karthik That's good to hear, do you think you could also update the `LICENSE` file? It currently only contains 
> YEAR: 2016
COPYRIGHT HOLDER: Karthik Ram

**Comment by kbroman** [comment]
R packages have weird rules about licenses. They are mostly indicated in the DESCRIPTION file, and just for the MIT license [we’re asked to provide](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing) just year and copyright holder in a LICENSE file.

**Comment by bryevdv** [comment]
Ah I did not know, thanks for the explanation.
