### ISSUE TITLE
How to remove segment lines in stack bar chart

### ISSUE THREAD

**Issue by mr2raccoon** [karthik/wesanderson#40]
Hey,

I really like your package!

I started using it and for some reason when I draw stacked bar plots each segment gets lines around them. This problem only appeared after using the "wesanderson"-package.

`ggplot(filterpie, aes(x=Sample, fill=species, y=Abundance))+
  geom_col(aes(color=species, fill=species), position="fill")+
  scale_fill_manual(values =wes_palette("BottleRocket1", 21, type = "continuous"))`

Is there a way to remove this?

![image](https://user-images.githubusercontent.com/81871773/114273077-00032c80-9a19-11eb-8705-a5c8c19b3871.png)

**Comment by karthik** [comment]
The color is from `species` as you have:

```
ggplot(filterpie, aes(x=Sample, fill=species, y=Abundance))+ geom_col(aes(color=species, fill=species), position="fill")+ scale_fill_manual(values =wes_palette("BottleRocket1", 21, type = "continuous"))
```

If you change it to:

```
ggplot(filterpie, aes(x = Sample, fill = species, y = Abundance)) + geom_col(aes(fill =
                                                                                   species), color = "black", position = "fill") + scale_fill_manual(values =
                                                                                                                                                       wes_palette("BottleRocket1", 21, type = "continuous"))
```

Then it will be the same color. I haven't tested the code as I don't have access to `filterpie`. Also note that since you have color inside `aes`, it will map to the legend. If you leave it outside `aes` as I have, then it wont.

**Comment by mr2raccoon** [comment]
Thanks for your help! I got the problem now!
