### ISSUE TITLE
Asteroid City Color Palettes

### ISSUE THREAD

**Issue by TheSupremeToast** [karthik/wesanderson#45]
Hi, first I just want to say I'm a big fan of both this package and Wes Anderson's movies.

I was hoping the new movie Asteroid City would bring new color palettes, but it seems the tumblr blog has not been updated for some time now, so I took the liberty of creating a few palettes of my own in a fork of this repo.
In case there is interest in adding these to the package, I will open a pr.

Keep up the good work!

**Comment by TheSupremeToast** [comment]
PR #46

**Comment by karthik** [comment]
Thank you! I merged it.
